pause_ad_blocking:
  name: Pause Ad Blocking
  description: Pause ad blocking for a specified number of seconds.
  fields:
    duration:
      description: Number of seconds to pause ad blocking
      example: 300
      required: true
      selector:
        number:
          min: 1
          max: 3600
